#spring.application.name=lucky_credit_app
spring:

  application:
    name: lucky_credit_app

  ai:
    openai:
      api-key: ${OPEN_ROUTER_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: mistralai/mistral-small-3.2-24b-instruct:free

  flyway:
    url: jdbc:postgresql://localhost:5432/lucky_credit_app
    schemas: lucky_credit_app
    user: postgres
    password: 2006Ahmad.
    locations: classpath:db/migration
    enabled: true
    driver-class-name: org.postgresql.Driver
    clean-disabled: false
  #    baseline-on-migrate: true


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      default_schema: lucky_credit_app
      format_sql: true


  datasource:
    url: jdbc:postgresql://localhost:5432/lucky_credit_app
    username: postgres
    password: 2006Ahmad.
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

paystack:
  secret:
    key: ${PAYSTACK_SECRET_KEY}